In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.shape

(569, 31)

In [6]:
#train-test-split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [7]:
#scaling
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [8]:
X_train

array([[-0.51731658, -1.57828533, -0.54551223, ..., -0.32233994,
        -0.12855876, -0.88316706],
       [ 1.21132578,  0.27530384,  1.2104232 , ...,  0.54230699,
         0.25806355, -0.30146893],
       [-0.47980013, -0.668465  , -0.37808096, ...,  0.28786543,
         0.50381134,  1.01800569],
       ...,
       [ 0.23301233, -1.00342373,  0.19118535, ..., -0.00746851,
        -0.34613163, -0.08306578],
       [ 0.38884987,  1.03801391,  0.49884031, ...,  1.53129708,
         0.16258193,  1.19379359],
       [ 1.41045153, -0.10265634,  1.31925352, ...,  0.10006334,
        -0.10664494, -1.0056859 ]])

In [9]:
y_train

170    B
516    M
485    B
466    B
281    B
      ..
536    M
91     M
472    B
509    M
127    M
Name: diagnosis, Length: 455, dtype: object

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1])

## Numpy Array to Pytorch Tensor

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

## Define the model

In [15]:
import torch.nn as nn
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,1),
        nn.Sigmoid()
    )

    # self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True)
    # self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    out = self.network(X)
    return out
    # z = torch.matmul(X, self.weights) + self.bias
    # y_pred = torch.sigmoid(z)
    # return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
    return -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred)).mean()

## important parameters

In [16]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

In [18]:
model = MySimpleNN(X_train_tensor.shape[1])
model = model.double() # Cast model parameters to float64
# model.weights, model.bias
# print(model.weights.shape)
# print(model.bias.shape)

#Define loop
for epoch in range(100):
  #forward pass
  y_pred = model(X_train_tensor)
  # y_pred = model.forward(X_train_tensor)
  # print(y_pred)

  #loss cal
  loss = model.loss_function(y_pred, y_train_tensor.double()) # Cast y_train_tensor to float64 for compatibility
  # print(loss)


  #backward
  loss.backward()

  #update params
  with torch.no_grad():
    for param in model.parameters():
      param -= learning_rate * param.grad
    # model.weights -= learning_rate * model.weights.grad
    # model.bias -= learning_rate * model.bias.grad

  #zero grad
  for param in model.parameters():
    param.grad.zero_()
  # model.weights.grad.zero_()
  # model.bias.grad.zero_()

  print(f'Epoch : {epoch+1}, Loss: {loss.item()}')

Epoch : 1, Loss: 0.8136446200750063
Epoch : 2, Loss: 0.770987838930243
Epoch : 3, Loss: 0.7452534049607905
Epoch : 4, Loss: 0.7303372102628063
Epoch : 5, Loss: 0.7215646809464916
Epoch : 6, Loss: 0.7160311628803575
Epoch : 7, Loss: 0.7121616461683079
Epoch : 8, Loss: 0.7091642959095815
Epoch : 9, Loss: 0.706653535621629
Epoch : 10, Loss: 0.704441914864189
Epoch : 11, Loss: 0.7024361246578825
Epoch : 12, Loss: 0.7005873237375241
Epoch : 13, Loss: 0.6988678517250927
Epoch : 14, Loss: 0.6972603739301867
Epoch : 15, Loss: 0.695752806405531
Epoch : 16, Loss: 0.6943359161020521
Epoch : 17, Loss: 0.6930021599035484
Epoch : 18, Loss: 0.6917451008041223
Epoch : 19, Loss: 0.6905590964655633
Epoch : 20, Loss: 0.6894391193799119
Epoch : 21, Loss: 0.6883806431125203
Epoch : 22, Loss: 0.6873795636725829
Epoch : 23, Loss: 0.6864321410117378
Epoch : 24, Loss: 0.6855349530834366
Epoch : 25, Loss: 0.6846848584183377
Epoch : 26, Loss: 0.6838789648890427
Epoch : 27, Loss: 0.6831146032128198
Epoch : 28, Loss: 0.6823893042145308
Epoch : 29, Loss: 0.6817007791476386
Epoch : 30, Loss: 0.6810469025445126
Epoch : 31, Loss: 0.6804256971842737
Epoch : 32, Loss: 0.6798353208500546
Epoch : 33, Loss: 0.6792740546099075
Epoch : 34, Loss: 0.6787402924034854
Epoch : 35, Loss: 0.6782325317541634
Epoch : 36, Loss: 0.6777493654561447
Epoch : 37, Loss: 0.6772894741101503
Epoch : 38, Loss: 0.6768516194008201
Epoch : 39, Loss: 0.6764346380249728
Epoch : 40, Loss: 0.6760374361930657
Epoch : 41, Loss: 0.6756589846371746
Epoch : 42, Loss: 0.6752983140679804
Epoch : 43, Loss: 0.6749545110309619
Epoch : 44, Loss: 0.6746267141185135
Epoch : 45, Loss: 0.674314110500239
Epoch : 46, Loss: 0.674015932738405
Epoch : 47, Loss: 0.673731455859583
Epoch : 48, Loss: 0.6734599946569945
Epoch : 49, Loss: 0.673200901201079
Epoch : 50, Loss: 0.6729535625384144
Epoch : 51, Loss: 0.6727173985613708
Epoch : 52, Loss: 0.6724918600328589
Epoch : 53, Loss: 0.6722764267522443
Epoch : 54, Loss: 0.6720706058500083
Epoch : 55, Loss: 0.6718739302000479
Epoch : 56, Loss: 0.6716859569396759
Epoch : 57, Loss: 0.6715062660883869
Epoch : 58, Loss: 0.6713344592573721
Epoch : 59, Loss: 0.6711701584425384
Epoch : 60, Loss: 0.6710130048945127
Epoch : 61, Loss: 0.6708626580597185
Epoch : 62, Loss: 0.6707187945871722
Epoch : 63, Loss: 0.670581107396142
Epoch : 64, Loss: 0.6704493048002427
Epoch : 65, Loss: 0.670323109683942
Epoch : 66, Loss: 0.6702022587277957
Epoch : 67, Loss: 0.6700865016790484
Epoch : 68, Loss: 0.6699756006645181
Epoch : 69, Loss: 0.6698693295429322
Epoch : 70, Loss: 0.6697674732941198
Epoch : 71, Loss: 0.6696698274426586
Epoch : 72, Loss: 0.6695761975137764
Epoch : 73, Loss: 0.6694863985194613
Epoch : 74, Loss: 0.6694002544728983
Epoch : 75, Loss: 0.6693175979294862
Epoch : 76, Loss: 0.6692382695528112
Epoch : 77, Loss: 0.6691621177040783
Epoch : 78, Loss: 0.6690889980535971
Epoch : 79, Loss: 0.6690187732130232
Epoch : 80, Loss: 0.6689513123871431
Epoch : 81, Loss: 0.6688864910440654
Epoch : 82, Loss: 0.6688241906027709
Epoch : 83, Loss: 0.6687642981370234
Epoch : 84, Loss: 0.6687067060947249
Epoch : 85, Loss: 0.6686513120318471
Epoch : 86, Loss: 0.6685980183601262
Epoch : 87, Loss: 0.6685467321077636
Epoch : 88, Loss: 0.668497364692417
Epoch : 89, Loss: 0.6684498317058105
Epoch : 90, Loss: 0.6684040527093346
Epoch : 91, Loss: 0.6683599510400421
Epoch : 92, Loss: 0.6683174536264842
Epoch : 93, Loss: 0.6682764908138568
Epoch : 94, Loss: 0.6682369961979687
Epoch : 95, Loss: 0.6681989064675592
Epoch : 96, Loss: 0.6681621612545282
Epoch : 97, Loss: 0.6681267029916634
Epoch : 98, Loss: 0.6680924767774724
Epoch : 99, Loss: 0.668059430247752
Epoch : 100, Loss: 0.6680275134535397

In [20]:
for params in model.parameters():
  print(params)

Parameter containing:
tensor([[-0.0444, -0.1062, -0.0009, -0.0242, -0.0359, -0.1099,  0.2005, -0.1049,
         -0.0219,  0.0649, -0.0132,  0.0027,  0.1465, -0.1383, -0.1096, -0.0383,
         -0.1234,  0.1178,  0.0570,  0.0602,  0.0173,  0.1028,  0.0818,  0.0003,
          0.0971,  0.1422, -0.0890, -0.0290, -0.0632, -0.1004]],
       dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.4171], dtype=torch.float64, requires_grad=True)

In [23]:
for idx, layer in enumerate(model.network):
  print(f"Layer {idx+1}: {layer}")

  if hasattr(layer, 'weight'):
    print(f"Weights: {layer.weight}")
  if hasattr(layer, 'bias'):
    print(f"Bias: {layer.bias}")

  print("="*40)

Layer 1: Linear(in_features=30, out_features=1, bias=True)
Weights: Parameter containing:
tensor([[-0.0444, -0.1062, -0.0009, -0.0242, -0.0359, -0.1099,  0.2005, -0.1049,
         -0.0219,  0.0649, -0.0132,  0.0027,  0.1465, -0.1383, -0.1096, -0.0383,
         -0.1234,  0.1178,  0.0570,  0.0602,  0.0173,  0.1028,  0.0818,  0.0003,
          0.0971,  0.1422, -0.0890, -0.0290, -0.0632, -0.1004]],
       dtype=torch.float64, requires_grad=True)
Bias: Parameter containing:
tensor([-0.4171], dtype=torch.float64, requires_grad=True)
========================================
Layer 2: Sigmoid()
========================================

## Evaluation

In [25]:
with torch.no_grad():
  y_pred = model(X_test_tensor)
  # y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()

  accuracy = (y_pred==y_test_tensor).float().mean()

print(f"Accuracy : {accuracy.item()}")
# print(y_pred, y_train_tensor)

Accuracy : 0.6723607182502747

# Using Linear Layer instead Of Sequential + builtIn gradient + builtIn loss fun

In [27]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, X):
    out = self.linear(X)
    out = self.sigmoid(out)
    return out

  # def loss_function(self, y_pred, y):
  #   epsilon = 1e-7
  #   y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
  #   return -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred)).mean()

  def accuracy(self, y_pred, y):
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred==y).float().mean()
    return accuracy

In [31]:
learning_rate = 0.1
epochs = 25

In [33]:
loss_function = nn.BCELoss()
# type(loss_function)

In [39]:
model = MySimpleNN(X_train_tensor.shape[1]).double()

optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

#Define loop
for epoch in range(100):
  #forward pass
  y_pred = model(X_train_tensor)

  #loss cal
  # loss = model.loss_function(y_pred, y_train_tensor)
  loss = loss_function(y_pred, y_train_tensor.view(-1,1).double())

  #zero grad (new)
  optimizer.zero_grad()

  #backward
  loss.backward()

  #update params
  # with torch.no_grad():
  #   model.linear.weight -= learning_rate * model.linear.weight.grad
  #   model.linear.bias -= learning_rate * model.linear.bias.grad

  optimizer.step()

  #zero grad
  #do befoe backward
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()

  print(f'Epoch : {epoch+1}, Loss: {loss.item()}')

Epoch : 1, Loss: 0.845485999385895
Epoch : 2, Loss: 0.605795377054797
Epoch : 3, Loss: 0.48522086545248083
Epoch : 4, Loss: 0.4162935270196905
Epoch : 5, Loss: 0.37133262937312395
Epoch : 6, Loss: 0.33926595122132663
Epoch : 7, Loss: 0.31496402230786635
Epoch : 8, Loss: 0.29573123959838515
Epoch : 9, Loss: 0.28001168822235345
Epoch : 10, Loss: 0.26684143455514053
Epoch : 11, Loss: 0.25558948887990157
Epoch : 12, Loss: 0.24582419227328567
Epoch : 13, Loss: 0.23723938890083
Epoch : 14, Loss: 0.2296112902692769
Epoch : 15, Loss: 0.22277207893978834
Epoch : 16, Loss: 0.21659311344288096
Epoch : 17, Loss: 0.2109738798596181
Epoch : 18, Loss: 0.2058345112259303
Epoch : 19, Loss: 0.20111059369307213
Epoch : 20, Loss: 0.19674947995996653
Epoch : 21, Loss: 0.19270762113445708
Epoch : 22, Loss: 0.18894860208063952
Epoch : 23, Loss: 0.18544167236700676
Epoch : 24, Loss: 0.18216063254709933
Epoch : 25, Loss: 0.17908297921771738
Epoch : 26, Loss: 0.17618924117317147
Epoch : 27, Loss: 0.17346245843027464
Epoch : 28, Loss: 0.17088776925610566
Epoch : 29, Loss: 0.1684520796610838
Epoch : 30, Loss: 0.1661437964417677
Epoch : 31, Loss: 0.1639526096245958
Epoch : 32, Loss: 0.16186931363601723
Epoch : 33, Loss: 0.15988565908344562
Epoch : 34, Loss: 0.15799422893296436
Epoch : 35, Loss: 0.15618833429299178
Epoch : 36, Loss: 0.1544619260850183
Epoch : 37, Loss: 0.15280951969418824
Epoch : 38, Loss: 0.15122613031023746
Epoch : 39, Loss: 0.14970721714185514
Epoch : 40, Loss: 0.14824863505101693
Epoch : 41, Loss: 0.1468465924350789
Epoch : 42, Loss: 0.14549761440347472
Epoch : 43, Loss: 0.1441985104677015
Epoch : 44, Loss: 0.14294634609913387
Epoch : 45, Loss: 0.14173841761748496
Epoch : 46, Loss: 0.14057222995975363
Epoch : 47, Loss: 0.13944547695002166
Epoch : 48, Loss: 0.13835602374808456
Epoch : 49, Loss: 0.13730189120235092
Epoch : 50, Loss: 0.13628124187180526
Epoch : 51, Loss: 0.13529236751470525
Epoch : 52, Loss: 0.13433367786931288
Epoch : 53, Loss: 0.13340369057530804
Epoch : 54, Loss: 0.13250102210436657
Epoch : 55, Loss: 0.13162437958530698
Epoch : 56, Loss: 0.13077255342370409
Epoch : 57, Loss: 0.1299444106283306
Epoch : 58, Loss: 0.12913888876753363
Epoch : 59, Loss: 0.1283549904879479
Epoch : 60, Loss: 0.12759177853600712
Epoch : 61, Loss: 0.12684837122971968
Epoch : 62, Loss: 0.1261239383342776
Epoch : 63, Loss: 0.1254176973003923
Epoch : 64, Loss: 0.12472890982890793
Epoch : 65, Loss: 0.12405687872932404
Epoch : 66, Loss: 0.1234009450434369
Epoch : 67, Loss: 0.12276048540845771
Epoch : 68, Loss: 0.12213490963673389
Epoch : 69, Loss: 0.12152365849164237
Epoch : 70, Loss: 0.12092620164138006
Epoch : 71, Loss: 0.12034203577428212
Epoch : 72, Loss: 0.11977068286098809
Epoch : 73, Loss: 0.11921168855027087
Epoch : 74, Loss: 0.11866462068667413
Epoch : 75, Loss: 0.11812906793928381
Epoch : 76, Loss: 0.11760463853201167
Epoch : 77, Loss: 0.11709095906670651
Epoch : 78, Loss: 0.11658767343124475
Epoch : 79, Loss: 0.11609444178549995
Epoch : 80, Loss: 0.11561093961876093
Epoch : 81, Loss: 0.11513685687276472
Epoch : 82, Loss: 0.11467189712505159
Epoch : 83, Loss: 0.1142157768278287
Epoch : 84, Loss: 0.1137682245979655
Epoch : 85, Loss: 0.11332898055413224
Epoch : 86, Loss: 0.11289779569744704
Epoch : 87, Loss: 0.11247443133231225
Epoch : 88, Loss: 0.11205865852440909
Epoch : 89, Loss: 0.11165025759307794
Epoch : 90, Loss: 0.11124901763554625
Epoch : 91, Loss: 0.11085473608067838
Epoch : 92, Loss: 0.1104672182701147
Epoch : 93, Loss: 0.11008627706484214
Epoch : 94, Loss: 0.10971173247539638
Epoch : 95, Loss: 0.10934341131404204
Epoch : 96, Loss: 0.10898114686740756
Epoch : 97, Loss: 0.10862477858817152
Epoch : 98, Loss: 0.10827415180450768
Epoch : 99, Loss: 0.10792911744609385
Epoch : 100, Loss: 0.10758953178558361

In [38]:
with torch.no_grad():
  y_pred = model(X_test_tensor)
  y_pred = (y_pred > 0.5).float()

  accuracy = (y_pred==y_test_tensor).float().mean()

print(f"Accuracy : {accuracy.item()}")
# print(y_pred, y_train_tensor)

Accuracy : 0.5584795475006104